# Generated by Django 5.0 on 2024-02-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateQuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_paper_name', models.CharField(max_length=250)),
                ('total_question', models.IntegerField()),
                ('exam_time', models.IntegerField()),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('English', 'English'), ('Other', 'Other')], default='Other', max_length=50)),
            ],
        ),
    ]
